setw -g mouse on
set-option -ga terminal-overrides ",foot:Tc"
set-option -ga terminal-overrides ",xterm-256color:Tc"
setw -g mode-keys vi
set -g history-limit 10000
set -sg escape-time 50
set -s set-clipboard on

set -g status-interval 30
set -g status-style "bg=black,fg=white"
setw -g window-status-current-style "fg=white,bg=blue,bright"
set -g status-position bottom

# status-right
set -g status-right-length 100
set -g status-right "#{user}@#{host} | #(date -d now '+%a/%b/%Y %R') "

set -g set-titles on
set -g set-titles-string "#{window_name} #{user}@#{host_short}"
set -g base-index 1

bind-key b set-option status
set -g lock-command vlock
bind L lock-session
bind R 'source-file $XDG_CONFIG_HOME/tmux/tmux.conf; display-message "source-file done"'
bind Tab last

bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
